### ISSUE TITLE
Business Name Label

### ISSUE THREAD

**Issue by hlpostman** [hlpostman/Yelp#1]
I have the line `businessNameLabel.preferredMaxLayoutWidth = businessNameLabel.frame.size.width` in the `awakeFromNib()`  and `layoutSubviews()` for my BusinessCell class as mentioned in CodePath's [Week 3 Video #2](https://youtu.be/N6qkyMNTYAA?t=10m54s) (link starts at 10:54).  But I have odd behavior exhibited in the screenshots below for Basil Thai Restaurant & Bar.  The label only displays correctly when it is selected, and then only if you have not scrolled it out of view:

**On load**:
Truncated

![1 on_load](https://cloud.githubusercontent.com/assets/13424868/22966422/fa598b74-f316-11e6-860c-ec7e894a90df.png)

**On selection**:
Correct

![2 on_selection](https://cloud.githubusercontent.com/assets/13424868/22966466/1a262b60-f317-11e6-9a65-cd654cbaf6e3.png)

**After scrolling the cell out of view and then back again**:
Wrapping, but on very narrow width (it stays this way if I select it too)

![3 after_scroll](https://cloud.githubusercontent.com/assets/13424868/22966479/2ea881be-f317-11e6-8e12-6fdb087c9e76.png)

**Comment by hlpostman** [comment]
Fixed in commit 8e2e55858fbe9b213e2528d13c073cdbf42f64b2 by removing the preferred max width lines.

**Comment by hlpostman** [comment]
Fixed in commit 8e2e55858fbe9b213e2528d13c073cdbf42f64b2 by removing the preferred max width lines.

**Comment by codepathreview** [comment]
:+1: Nice work! This primary challenge of this homework was to learn how to use AutoLayout to build adaptive UI's that work across many different screen sizes and orientations. If you haven't already, we recommend going back and running your homework again while rotating the device / simulator to ensure your AutoLayout constraints function as expected.

We have a detailed [Project 3 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_3_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

Check out the [project rubric](https://courses.codepath.com/snippets/ios_university/project_rubric.md) for a breakdown of how submissions are scored.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at <universitysupport@codepath.com>.
